import { createStixBundleFromIocs, downloadJsonFile } from '../utils/stixExporter';
export class DetectionRuleExporter {
    containerId;
    constructor(containerId) {
        this.containerId = containerId;
    }
    render() {
        const container = document.getElementById(this.containerId);
        if (!container)
            return;
        container.innerHTML = `
      <div class="panel-header">
        <span>⚡ NEXT-GEN SIEM & EDR RULE EXPORTER</span>
        <span style="font-size: 10px; color: var(--accent-green);">KQL • YARA-L 2.0 • LQL</span>
      </div>
      <div class="panel-body">
        <div style="font-size: 10px; color: var(--text-muted); margin-bottom: 8px;">
          Export live CTI threat indicators into cloud-native SIEM & EDR query formats:
        </div>

        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; margin-bottom: 8px;">
          <button id="btn-export-stix" style="padding: 6px; background: rgba(56,189,248,0.15); border: 1px solid var(--accent-blue); color: var(--accent-blue); border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">📦 STIX 2.1</div>
            <div style="font-size: 7px; color: var(--text-muted);">For OpenCTI/MISP</div>
          </button>

          <button id="btn-export-kql" style="padding: 6px; background: rgba(56,189,248,0.15); border: 1px solid #0284c7; color: #38bdf8; border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">🔍 MS Sentinel KQL</div>
            <div style="font-size: 7px; color: var(--text-muted);">Microsoft Defender</div>
          </button>

          <button id="btn-export-yaral" style="padding: 6px; background: rgba(168,85,247,0.15); border: 1px solid #a855f7; color: #c084fc; border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">📦 YARA-L 2.0</div>
            <div style="font-size: 7px; color: var(--text-muted);">Google SecOps</div>
          </button>

          <button id="btn-export-lql" style="padding: 6px; background: rgba(239,68,68,0.15); border: 1px solid var(--accent-red); color: var(--accent-red); border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">🦅 CrowdStrike LQL</div>
            <div style="font-size: 7px; color: var(--text-muted);">Falcon LogScale</div>
          </button>

          <button id="btn-export-sigma" style="padding: 6px; background: rgba(74,222,128,0.15); border: 1px solid var(--accent-green); color: var(--accent-green); border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">🛡️ Sigma Rules</div>
            <div style="font-size: 7px; color: var(--text-muted);">Universal SIEM</div>
          </button>

          <button id="btn-export-yara" style="padding: 6px; background: rgba(234,179,8,0.15); border: 1px solid #eab308; color: #eab308; border-radius: 3px; font-family: var(--font-mono); font-size: 9px; cursor: pointer; text-align: left;">
            <div style="font-weight: bold;">🔍 YARA Rules</div>
            <div style="font-size: 7px; color: var(--text-muted);">Endpoint Scanning</div>
          </button>
        </div>
      </div>
    `;
        this.attachEvents(container);
    }
    attachEvents(container) {
        const sampleIocs = [
            { indicator: '185.220.101.5', type: 'ip', severity: 'critical' },
            { indicator: '198.51.100.24', type: 'ip', severity: 'high' },
            { indicator: '91.215.85.12', type: 'ip', severity: 'high' },
        ];
        container.querySelector('#btn-export-stix')?.addEventListener('click', () => {
            const bundle = createStixBundleFromIocs(sampleIocs);
            downloadJsonFile('cti-stix-2.1-bundle.json', bundle);
        });
        container.querySelector('#btn-export-kql')?.addEventListener('click', () => {
            const kqlQuery = `// Microsoft Sentinel / Defender KQL Query generated by CTI Monitor
let c2_ips = dynamic(["185.220.101.5", "198.51.100.24", "91.215.85.12"]);
NetworkCommunicationEvents
| where RemoteIP in (c2_ips)
| project TimeGenerated, DeviceName, LocalIP, RemoteIP, RemotePort, InitiatingProcessFileName
| extend ThreatLevel = "CRITICAL_C2_MATCH"
`;
            const blob = new Blob([kqlQuery], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'cti-sentinel-c2-detection.kql';
            a.click();
            URL.revokeObjectURL(url);
        });
        container.querySelector('#btn-export-yaral')?.addEventListener('click', () => {
            const yaralRule = `// Google SecOps / Chronicle YARA-L 2.0 Rule generated by CTI Monitor
rule cti_c2_botnet_detection {
  meta:
    author = "CTI Monitor Exporter"
    description = "Detects network connection to active Feodo C2 botnet nodes"
    severity = "CRITICAL"
  events:
    $net.metadata.event_type = "NETWORK_CONNECTION"
    $net.principal.ip = $local_ip
    $net.target.ip = $remote_ip
    $remote_ip in ["185.220.101.5", "198.51.100.24", "91.215.85.12"]
  condition:
    $net
}
`;
            const blob = new Blob([yaralRule], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'cti-google-secops-c2.yaral';
            a.click();
            URL.revokeObjectURL(url);
        });
        container.querySelector('#btn-export-lql')?.addEventListener('click', () => {
            const lqlQuery = `# CrowdStrike Falcon LogScale / LQL Query generated by CTI Monitor
#event_simple_name = /NetworkConnect/ 
| in(field=RemoteAddressIP4, values=["185.220.101.5", "198.51.100.24", "91.215.85.12"])
| table([@timestamp, ComputerName, LocalAddressIP4, RemoteAddressIP4, RemotePort, ImageFileName])
`;
            const blob = new Blob([lqlQuery], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'cti-crowdstrike-logscale.lql';
            a.click();
            URL.revokeObjectURL(url);
        });
        container.querySelector('#btn-export-sigma')?.addEventListener('click', () => {
            const sigmaYaml = `title: Detect Active C2 Infrastructure Connections
id: ${crypto.randomUUID ? crypto.randomUUID() : 'sigma-rule-1'}
status: experimental
description: Detects outgoing connections to active botnet C2 servers
logsource:
  category: network_connection
  product: windows
detection:
  selection:
    DestinationIp:
      - '185.220.101.5'
      - '198.51.100.24'
      - '91.215.85.12'
  condition: selection
level: high
`;
            const blob = new Blob([sigmaYaml], { type: 'text/yaml' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'cti-c2-detection-sigma.yml';
            a.click();
            URL.revokeObjectURL(url);
        });
        container.querySelector('#btn-export-yara')?.addEventListener('click', () => {
            const yaraRule = `rule CTI_Observed_Malware_Memory {
  meta:
    description = "YARA Rule generated by CTI Monitor for CobaltStrike / Feodo C2"
    author = "CTI Monitor Exporter"
    date = "${new Date().toISOString().split('T')[0]}"
  strings:
    $s1 = "185.220.101.5" ascii
    $s2 = "198.51.100.24" ascii
  condition:
    any of ($s*)
}`;
            const blob = new Blob([yaraRule], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'cti-malware-rule.yar';
            a.click();
            URL.revokeObjectURL(url);
        });
    }
}
