export function createStixBundleFromIocs(iocs) {
    const now = new Date().toISOString();
    const objects = iocs.map((item, idx) => ({
        type: 'indicator',
        spec_version: '2.1',
        id: `indicator--${crypto.randomUUID ? crypto.randomUUID() : 'ioc-' + idx + '-' + Date.now()}`,
        created: now,
        modified: now,
        name: `Observed ${item.type.toUpperCase()} Indicator: ${item.indicator}`,
        description: `STIX 2.1 Indicator generated by CTI Monitor (${item.severity || 'high'} severity)`,
        pattern: `[domain-name:value = '${item.indicator}'] OR [ipv4-addr:value = '${item.indicator}']`,
        pattern_type: 'stix',
        valid_from: now,
        labels: [item.type, item.severity || 'medium'],
    }));
    return {
        type: 'bundle',
        id: `bundle--${crypto.randomUUID ? crypto.randomUUID() : 'cti-bundle-' + Date.now()}`,
        objects,
    };
}
export function downloadJsonFile(filename, data) {
    const jsonStr = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
